apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkinsdeployment
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 4
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
